### ISSUE TITLE
[Android Bootcamp] Project 2 - Review my app [Instagram_Photo_Viewer]

### ISSUE THREAD

**Issue by TienVNguyen** [TienVNguyen/Android#1]
My app [Instagram_Photo_Viewer] is completed. Please help to review and accept it!
- Implement link: https://github.com/TienVNguyen/Android/tree/master/CoderSchool_VN/Classes/1_Exercise/Instagram_Photo_Viewer
- App link: https://github.com/TienVNguyen/Android/tree/master/CoderSchool_VN/Classes/1_Exercise/Instagram_Photo_Viewer
- Location: /Android/CoderSchool_VN/Classes/1_Exercise/Instagram_Photo_Viewer/

/cc @coderschoolreview
/cc @hoanle

Ps: I will update for more on the next two days if it is possible.
Thanks & Best Regards,
Tien Nguyen

**Comment by TienVNguyen** [comment]
Hi all,

I just updated for some small cases. So, please help to pull the latest version of source.

Thanks & Best Regards,
Tien Nguyen

**Comment by hoanle** [comment]
@TienVNguyen 

Please update the project separately next time. Its looks great

Good points:
- You almost finish all of the tasks, both required and optional
- Nice playing with different layout type. Especially RelativeLayout, the most powerful and popular of all.
- Nice to see you used the SwipeRefreshLayout for easy stream refreshes
- Good job using the ButterKnife library annotations for declaring handles to view objects. However, there are many places you still use normal way of access View
- Good to see that you were able to successfully read the json object to display comments for photos.

Suggestion:
- Consider using the ViewHolder pattern to improve performance of photos ListView.
- Consider overriding onFailure method handle network failures appropriately.
- The code is quite messy. For example, there are tons of code in onSuccess of fetching image. It's very hard to read those code. GSon might help in this case
- Again, too many comments, even in places where you have commented the code or places where the code is very obvious
For example:

```
 /* Fragment */
CommentsDialogFragment commentsDialogFragment = new CommentsDialogFragment();

 // Initialize
 photoObjects = new ArrayList<>();

```

How about divide the code into smaller and clearer functions?

**Comment by TienVNguyen** [comment]
Hi @hoanle

I totally agree to your suggestion. I intent to complete all the tasks as much as possible then reconstruct the project later. That's why my code is a big mess =_=. Luckily you can scan through some of them :+1: 
As the result, some update will be submitted at this evening to enhance the source and apply some of your suggestion if it is possible :+1: 

Thanks & Best Regards,
Tien Nguyen

**Comment by TienVNguyen** [comment]
Hi @hoanle

I just updated source code to apply your suggestion except for GSon. So, I think I will apply this to another exercises later.

Thanks & Best Regards,
Tien Nguyen
